---------------------------------------------------------------------------------------------------------
Problem              inst_100_50_100_50_75_25_45$_09_7.cmpl
Nr. of variables     1000000
Nr. of constraints   15050
Objective name       cost
Solver name          GLPK
Display variables    nonzero variables (all)
Display constraints  nonzero constraints (all)
---------------------------------------------------------------------------------------------------------

Objective status     optimal
Objective value      53888 (min!)

Variables 
Name                 Type            Activity         Lower bound         Upper bound            Marginal
---------------------------------------------------------------------------------------------------------
y[1,66,53,2]            I                   1                   0                   1                   -
y[1,68,66,1]            I                   1                   0                   1                   -
y[2,75,96,2]            I                   1                   0                   1                   -
y[2,96,100,1]           I                   1                   0                   1                   -
y[3,95,21,2]            I                   1                   0                   1                   -
y[4,79,49,2]            I                   1                   0                   1                   -
y[4,84,79,1]            I                   1                   0                   1                   -
y[5,11,10,1]            I                   1                   0                   1                   -
y[5,34,11,2]            I                   1                   0                   1                   -
y[5,47,34,2]            I                   1                   0                   1                   -
y[5,48,47,1]            I                   1                   0                   1                   -
y[6,44,46,1]            I                   1                   0                   1                   -
y[6,65,44,2]            I                   1                   0                   1                   -
y[7,66,82,2]            I                   1                   0                   1                   -
y[7,82,86,1]            I                   1                   0                   1                   -
y[8,34,11,2]            I                   1                   0                   1                   -
y[9,77,70,2]            I                   1                   0                   1                   -
y[9,84,77,1]            I                   1                   0                   1                   -
y[10,10,9,1]            I                   1                   0                   1                   -
y[10,52,10,2]           I                   1                   0                   1                   -
y[10,86,52,2]           I                   1                   0                   1                   -
y[11,26,27,1]           I                   1                   0                   1                   -
y[11,27,82,2]           I                   1                   0                   1                   -
y[11,82,84,1]           I                   1                   0                   1                   -
y[12,76,78,1]           I                   1                   0                   1                   -
y[12,78,51,2]           I                   1                   0                   1                   -
y[13,58,56,1]           I                   1                   0                   1                   -
y[13,82,58,2]           I                   1                   0                   1                   -
y[14,2,1,1]             I                   1                   0                   1                   -
y[14,25,2,2]            I                   1                   0                   1                   -
y[15,64,25,2]           I                   1                   0                   1                   -
y[15,65,64,1]           I                   1                   0                   1                   -
y[16,77,78,1]           I                   1                   0                   1                   -
y[17,11,8,1]            I                   1                   0                   1                   -
y[17,30,11,2]           I                   1                   0                   1                   -
y[17,31,30,1]           I                   1                   0                   1                   -
y[18,71,73,1]           I                   1                   0                   1                   -
y[19,17,18,1]           I                   1                   0                   1                   -
y[19,38,17,2]           I                   1                   0                   1                   -
y[19,57,38,2]           I                   1                   0                   1                   -
y[20,58,24,2]           I                   1                   0                   1                   -
y[21,53,51,1]           I                   1                   0                   1                   -
y[21,71,53,2]           I                   1                   0                   1                   -
y[22,62,17,2]           I                   1                   0                   1                   -
y[22,64,62,1]           I                   1                   0                   1                   -
y[22,99,64,2]           I                   1                   0                   1                   -
y[23,69,61,2]           I                   1                   0                   1                   -
y[23,78,69,2]           I                   1                   0                   1                   -
y[24,39,61,2]           I                   1                   0                   1                   -
y[24,40,39,1]           I                   1                   0                   1                   -
y[25,42,45,1]           I                   1                   0                   1                   -
y[25,45,65,2]           I                   1                   0                   1                   -
y[26,6,5,1]             I                   1                   0                   1                   -
y[26,47,6,2]            I                   1                   0                   1                   -
y[27,47,94,2]           I                   1                   0                   1                   -
y[28,82,51,2]           I                   1                   0                   1                   -
y[29,41,81,2]           I                   1                   0                   1                   -
y[29,81,84,1]           I                   1                   0                   1                   -
y[30,69,32,2]           I                   1                   0                   1                   -
y[30,78,69,2]           I                   1                   0                   1                   -
y[30,79,78,1]           I                   1                   0                   1                   -
y[31,4,3,1]             I                   1                   0                   1                   -
y[31,40,4,2]            I                   1                   0                   1                   -
y[31,41,40,1]           I                   1                   0                   1                   -
y[32,71,22,2]           I                   1                   0                   1                   -
y[32,74,71,1]           I                   1                   0                   1                   -
y[33,29,14,2]           I                   1                   0                   1                   -
y[33,31,29,1]           I                   1                   0                   1                   -
y[34,22,21,1]           I                   1                   0                   1                   -
y[34,65,22,2]           I                   1                   0                   1                   -
y[35,50,32,2]           I                   1                   0                   1                   -
y[36,2,1,1]             I                   1                   0                   1                   -
y[36,25,2,2]            I                   1                   0                   1                   -
y[36,26,25,1]           I                   1                   0                   1                   -
y[37,2,45,2]            I                   1                   0                   1                   -
y[37,45,80,2]           I                   1                   0                   1                   -
y[38,80,99,2]           I                   1                   0                   1                   -
y[39,38,35,1]           I                   1                   0                   1                   -
y[39,57,38,2]           I                   1                   0                   1                   -
y[39,58,57,1]           I                   1                   0                   1                   -
y[40,41,42,1]           I                   1                   0                   1                   -
y[40,42,70,2]           I                   1                   0                   1                   -
y[40,70,79,2]           I                   1                   0                   1                   -
y[41,73,97,2]           I                   1                   0                   1                   -
y[42,72,74,2]           I                   1                   0                   1                   -
y[42,74,80,2]           I                   1                   0                   1                   -
y[42,80,85,1]           I                   1                   0                   1                   -
y[43,24,43,2]           I                   1                   0                   1                   -
y[43,43,57,2]           I                   1                   0                   1                   -
y[43,57,59,1]           I                   1                   0                   1                   -
y[44,47,48,1]           I                   1                   0                   1                   -
y[45,43,70,2]           I                   1                   0                   1                   -
y[45,70,69,1]           I                   1                   0                   1                   -
y[46,73,67,1]           I                   1                   0                   1                   -
y[47,19,36,2]           I                   1                   0                   1                   -
y[47,36,37,1]           I                   1                   0                   1                   -
y[48,90,74,1]           I                   1                   0                   1                   -
y[49,50,51,1]           I                   1                   0                   1                   -
y[49,51,95,2]           I                   1                   0                   1                   -
y[49,95,96,1]           I                   1                   0                   1                   -
y[50,31,29,1]           I                   1                   0                   1                   -
y[50,33,31,1]           I                   1                   0                   1                   -
y[50,80,33,2]           I                   1                   0                   1                   -
---------------------------------------------------------------------------------------------------------

Constraints 
Name                 Type            Activity         Lower bound         Upper bound            Marginal
---------------------------------------------------------------------------------------------------------
bilancio[1,14]          E                   1                   1                   1                   -
bilancio[1,36]          E                   1                   1                   1                   -
bilancio[2,37]          E                  -1                  -1                  -1                   -
bilancio[3,31]          E                   1                   1                   1                   -
bilancio[5,26]          E                   1                   1                   1                   -
bilancio[8,17]          E                   1                   1                   1                   -
bilancio[9,10]          E                   1                   1                   1                   -
bilancio[10,5]          E                   1                   1                   1                   -
bilancio[11,8]          E                   1                   1                   1                   -
bilancio[14,33]         E                   1                   1                   1                   -
bilancio[17,22]         E                   1                   1                   1                   -
bilancio[18,19]         E                   1                   1                   1                   -
bilancio[19,47]         E                  -1                  -1                  -1                   -
bilancio[21,3]          E                   1                   1                   1                   -
bilancio[21,34]         E                   1                   1                   1                   -
bilancio[22,32]         E                   1                   1                   1                   -
bilancio[24,20]         E                   1                   1                   1                   -
bilancio[24,43]         E                  -1                  -1                  -1                   -
bilancio[25,14]         E                  -1                  -1                  -1                   -
bilancio[25,15]         E                   1                   1                   1                   -
bilancio[26,11]         E                  -1                  -1                  -1                   -
bilancio[26,36]         E                  -1                  -1                  -1                   -
bilancio[29,50]         E                   1                   1                   1                   -
bilancio[31,17]         E                  -1                  -1                  -1                   -
bilancio[31,33]         E                  -1                  -1                  -1                   -
bilancio[32,30]         E                   1                   1                   1                   -
bilancio[32,35]         E                   1                   1                   1                   -
bilancio[34,8]          E                  -1                  -1                  -1                   -
bilancio[35,39]         E                   1                   1                   1                   -
bilancio[37,47]         E                   1                   1                   1                   -
bilancio[40,24]         E                  -1                  -1                  -1                   -
bilancio[41,29]         E                  -1                  -1                  -1                   -
bilancio[41,31]         E                  -1                  -1                  -1                   -
bilancio[41,40]         E                  -1                  -1                  -1                   -
bilancio[42,25]         E                  -1                  -1                  -1                   -
bilancio[43,45]         E                  -1                  -1                  -1                   -
bilancio[46,6]          E                   1                   1                   1                   -
bilancio[47,26]         E                  -1                  -1                  -1                   -
bilancio[47,27]         E                  -1                  -1                  -1                   -
bilancio[47,44]         E                  -1                  -1                  -1                   -
bilancio[48,5]          E                  -1                  -1                  -1                   -
bilancio[48,44]         E                   1                   1                   1                   -
bilancio[49,4]          E                   1                   1                   1                   -
bilancio[50,35]         E                  -1                  -1                  -1                   -
bilancio[50,49]         E                  -1                  -1                  -1                   -
bilancio[51,12]         E                   1                   1                   1                   -
bilancio[51,21]         E                   1                   1                   1                   -
bilancio[51,28]         E                   1                   1                   1                   -
bilancio[53,1]          E                   1                   1                   1                   -
bilancio[56,13]         E                   1                   1                   1                   -
bilancio[57,19]         E                  -1                  -1                  -1                   -
bilancio[58,20]         E                  -1                  -1                  -1                   -
bilancio[58,39]         E                  -1                  -1                  -1                   -
bilancio[59,43]         E                   1                   1                   1                   -
bilancio[61,23]         E                   1                   1                   1                   -
bilancio[61,24]         E                   1                   1                   1                   -
bilancio[65,6]          E                  -1                  -1                  -1                   -
bilancio[65,15]         E                  -1                  -1                  -1                   -
bilancio[65,25]         E                   1                   1                   1                   -
bilancio[65,34]         E                  -1                  -1                  -1                   -
bilancio[66,7]          E                  -1                  -1                  -1                   -
bilancio[67,46]         E                   1                   1                   1                   -
bilancio[68,1]          E                  -1                  -1                  -1                   -
bilancio[69,45]         E                   1                   1                   1                   -
bilancio[70,9]          E                   1                   1                   1                   -
bilancio[71,18]         E                  -1                  -1                  -1                   -
bilancio[71,21]         E                  -1                  -1                  -1                   -
bilancio[72,42]         E                  -1                  -1                  -1                   -
bilancio[73,18]         E                   1                   1                   1                   -
bilancio[73,41]         E                  -1                  -1                  -1                   -
bilancio[73,46]         E                  -1                  -1                  -1                   -
bilancio[74,32]         E                  -1                  -1                  -1                   -
bilancio[74,48]         E                   1                   1                   1                   -
bilancio[75,2]          E                  -1                  -1                  -1                   -
bilancio[76,12]         E                  -1                  -1                  -1                   -
bilancio[77,16]         E                  -1                  -1                  -1                   -
bilancio[78,16]         E                   1                   1                   1                   -
bilancio[78,23]         E                  -1                  -1                  -1                   -
bilancio[79,30]         E                  -1                  -1                  -1                   -
bilancio[79,40]         E                   1                   1                   1                   -
bilancio[80,37]         E                   1                   1                   1                   -
bilancio[80,38]         E                  -1                  -1                  -1                   -
bilancio[80,50]         E                  -1                  -1                  -1                   -
bilancio[82,13]         E                  -1                  -1                  -1                   -
bilancio[82,28]         E                  -1                  -1                  -1                   -
bilancio[84,4]          E                  -1                  -1                  -1                   -
bilancio[84,9]          E                  -1                  -1                  -1                   -
bilancio[84,11]         E                   1                   1                   1                   -
bilancio[84,29]         E                   1                   1                   1                   -
bilancio[85,42]         E                   1                   1                   1                   -
bilancio[86,7]          E                   1                   1                   1                   -
bilancio[86,10]         E                  -1                  -1                  -1                   -
bilancio[90,48]         E                  -1                  -1                  -1                   -
bilancio[94,27]         E                   1                   1                   1                   -
bilancio[95,3]          E                  -1                  -1                  -1                   -
bilancio[96,49]         E                   1                   1                   1                   -
bilancio[97,41]         E                   1                   1                   1                   -
bilancio[99,22]         E                  -1                  -1                  -1                   -
bilancio[99,38]         E                   1                   1                   1                   -
bilancio[100,2]         E                   1                   1                   1                   -
lunghezza[1]            L                   2           -Infinity                   7                   -
lunghezza[2]            L                   2           -Infinity                   7                   -
lunghezza[3]            L                   1           -Infinity                   7                   -
lunghezza[4]            L                   2           -Infinity                   7                   -
lunghezza[5]            L                   4           -Infinity                   7                   -
lunghezza[6]            L                   2           -Infinity                   7                   -
lunghezza[7]            L                   2           -Infinity                   7                   -
lunghezza[8]            L                   1           -Infinity                   7                   -
lunghezza[9]            L                   2           -Infinity                   7                   -
lunghezza[10]           L                   3           -Infinity                   7                   -
lunghezza[11]           L                   3           -Infinity                   7                   -
lunghezza[12]           L                   2           -Infinity                   7                   -
lunghezza[13]           L                   2           -Infinity                   7                   -
lunghezza[14]           L                   2           -Infinity                   7                   -
lunghezza[15]           L                   2           -Infinity                   7                   -
lunghezza[16]           L                   1           -Infinity                   7                   -
lunghezza[17]           L                   3           -Infinity                   7                   -
lunghezza[18]           L                   1           -Infinity                   7                   -
lunghezza[19]           L                   3           -Infinity                   7                   -
lunghezza[20]           L                   1           -Infinity                   7                   -
lunghezza[21]           L                   2           -Infinity                   7                   -
lunghezza[22]           L                   3           -Infinity                   7                   -
lunghezza[23]           L                   2           -Infinity                   7                   -
lunghezza[24]           L                   2           -Infinity                   7                   -
lunghezza[25]           L                   2           -Infinity                   7                   -
lunghezza[26]           L                   2           -Infinity                   7                   -
lunghezza[27]           L                   1           -Infinity                   7                   -
lunghezza[28]           L                   1           -Infinity                   7                   -
lunghezza[29]           L                   2           -Infinity                   7                   -
lunghezza[30]           L                   3           -Infinity                   7                   -
lunghezza[31]           L                   3           -Infinity                   7                   -
lunghezza[32]           L                   2           -Infinity                   7                   -
lunghezza[33]           L                   2           -Infinity                   7                   -
lunghezza[34]           L                   2           -Infinity                   7                   -
lunghezza[35]           L                   1           -Infinity                   7                   -
lunghezza[36]           L                   3           -Infinity                   7                   -
lunghezza[37]           L                   2           -Infinity                   7                   -
lunghezza[38]           L                   1           -Infinity                   7                   -
lunghezza[39]           L                   3           -Infinity                   7                   -
lunghezza[40]           L                   3           -Infinity                   7                   -
lunghezza[41]           L                   1           -Infinity                   7                   -
lunghezza[42]           L                   3           -Infinity                   7                   -
lunghezza[43]           L                   3           -Infinity                   7                   -
lunghezza[44]           L                   1           -Infinity                   7                   -
lunghezza[45]           L                   2           -Infinity                   7                   -
lunghezza[46]           L                   1           -Infinity                   7                   -
lunghezza[47]           L                   2           -Infinity                   7                   -
lunghezza[48]           L                   1           -Infinity                   7                   -
lunghezza[49]           L                   3           -Infinity                   7                   -
lunghezza[50]           L                   3           -Infinity                   7                   -
unico[1,66,2]           L                   1           -Infinity                   1                   -
unico[1,68,1]           L                   1           -Infinity                   1                   -
unico[2,75,2]           L                   1           -Infinity                   1                   -
unico[2,96,1]           L                   1           -Infinity                   1                   -
unico[3,95,2]           L                   1           -Infinity                   1                   -
unico[4,79,2]           L                   1           -Infinity                   1                   -
unico[4,84,1]           L                   1           -Infinity                   1                   -
unico[5,11,1]           L                   1           -Infinity                   1                   -
unico[5,34,2]           L                   1           -Infinity                   1                   -
unico[5,47,2]           L                   1           -Infinity                   1                   -
unico[5,48,1]           L                   1           -Infinity                   1                   -
unico[6,44,1]           L                   1           -Infinity                   1                   -
unico[6,65,2]           L                   1           -Infinity                   1                   -
unico[7,66,2]           L                   1           -Infinity                   1                   -
unico[7,82,1]           L                   1           -Infinity                   1                   -
unico[8,34,2]           L                   1           -Infinity                   1                   -
unico[9,77,2]           L                   1           -Infinity                   1                   -
unico[9,84,1]           L                   1           -Infinity                   1                   -
unico[10,10,1]          L                   1           -Infinity                   1                   -
unico[10,52,2]          L                   1           -Infinity                   1                   -
unico[10,86,2]          L                   1           -Infinity                   1                   -
unico[11,26,1]          L                   1           -Infinity                   1                   -
unico[11,27,2]          L                   1           -Infinity                   1                   -
unico[11,82,1]          L                   1           -Infinity                   1                   -
unico[12,76,1]          L                   1           -Infinity                   1                   -
unico[12,78,2]          L                   1           -Infinity                   1                   -
unico[13,58,1]          L                   1           -Infinity                   1                   -
unico[13,82,2]          L                   1           -Infinity                   1                   -
unico[14,2,1]           L                   1           -Infinity                   1                   -
unico[14,25,2]          L                   1           -Infinity                   1                   -
unico[15,64,2]          L                   1           -Infinity                   1                   -
unico[15,65,1]          L                   1           -Infinity                   1                   -
unico[16,77,1]          L                   1           -Infinity                   1                   -
unico[17,11,1]          L                   1           -Infinity                   1                   -
unico[17,30,2]          L                   1           -Infinity                   1                   -
unico[17,31,1]          L                   1           -Infinity                   1                   -
unico[18,71,1]          L                   1           -Infinity                   1                   -
unico[19,17,1]          L                   1           -Infinity                   1                   -
unico[19,38,2]          L                   1           -Infinity                   1                   -
unico[19,57,2]          L                   1           -Infinity                   1                   -
unico[20,58,2]          L                   1           -Infinity                   1                   -
unico[21,53,1]          L                   1           -Infinity                   1                   -
unico[21,71,2]          L                   1           -Infinity                   1                   -
unico[22,62,2]          L                   1           -Infinity                   1                   -
unico[22,64,1]          L                   1           -Infinity                   1                   -
unico[22,99,2]          L                   1           -Infinity                   1                   -
unico[23,69,2]          L                   1           -Infinity                   1                   -
unico[23,78,2]          L                   1           -Infinity                   1                   -
unico[24,39,2]          L                   1           -Infinity                   1                   -
unico[24,40,1]          L                   1           -Infinity                   1                   -
unico[25,42,1]          L                   1           -Infinity                   1                   -
unico[25,45,2]          L                   1           -Infinity                   1                   -
unico[26,6,1]           L                   1           -Infinity                   1                   -
unico[26,47,2]          L                   1           -Infinity                   1                   -
unico[27,47,2]          L                   1           -Infinity                   1                   -
unico[28,82,2]          L                   1           -Infinity                   1                   -
unico[29,41,2]          L                   1           -Infinity                   1                   -
unico[29,81,1]          L                   1           -Infinity                   1                   -
unico[30,69,2]          L                   1           -Infinity                   1                   -
unico[30,78,2]          L                   1           -Infinity                   1                   -
unico[30,79,1]          L                   1           -Infinity                   1                   -
unico[31,4,1]           L                   1           -Infinity                   1                   -
unico[31,40,2]          L                   1           -Infinity                   1                   -
unico[31,41,1]          L                   1           -Infinity                   1                   -
unico[32,71,2]          L                   1           -Infinity                   1                   -
unico[32,74,1]          L                   1           -Infinity                   1                   -
unico[33,29,2]          L                   1           -Infinity                   1                   -
unico[33,31,1]          L                   1           -Infinity                   1                   -
unico[34,22,1]          L                   1           -Infinity                   1                   -
unico[34,65,2]          L                   1           -Infinity                   1                   -
unico[35,50,2]          L                   1           -Infinity                   1                   -
unico[36,2,1]           L                   1           -Infinity                   1                   -
unico[36,25,2]          L                   1           -Infinity                   1                   -
unico[36,26,1]          L                   1           -Infinity                   1                   -
unico[37,2,2]           L                   1           -Infinity                   1                   -
unico[37,45,2]          L                   1           -Infinity                   1                   -
unico[38,80,2]          L                   1           -Infinity                   1                   -
unico[39,38,1]          L                   1           -Infinity                   1                   -
unico[39,57,2]          L                   1           -Infinity                   1                   -
unico[39,58,1]          L                   1           -Infinity                   1                   -
unico[40,41,1]          L                   1           -Infinity                   1                   -
unico[40,42,2]          L                   1           -Infinity                   1                   -
unico[40,70,2]          L                   1           -Infinity                   1                   -
unico[41,73,2]          L                   1           -Infinity                   1                   -
unico[42,72,2]          L                   1           -Infinity                   1                   -
unico[42,74,2]          L                   1           -Infinity                   1                   -
unico[42,80,1]          L                   1           -Infinity                   1                   -
unico[43,24,2]          L                   1           -Infinity                   1                   -
unico[43,43,2]          L                   1           -Infinity                   1                   -
unico[43,57,1]          L                   1           -Infinity                   1                   -
unico[44,47,1]          L                   1           -Infinity                   1                   -
unico[45,43,2]          L                   1           -Infinity                   1                   -
unico[45,70,1]          L                   1           -Infinity                   1                   -
unico[46,73,1]          L                   1           -Infinity                   1                   -
unico[47,19,2]          L                   1           -Infinity                   1                   -
unico[47,36,1]          L                   1           -Infinity                   1                   -
unico[48,90,1]          L                   1           -Infinity                   1                   -
unico[49,50,1]          L                   1           -Infinity                   1                   -
unico[49,51,2]          L                   1           -Infinity                   1                   -
unico[49,95,1]          L                   1           -Infinity                   1                   -
unico[50,31,1]          L                   1           -Infinity                   1                   -
unico[50,33,1]          L                   1           -Infinity                   1                   -
unico[50,80,2]          L                   1           -Infinity                   1                   -
---------------------------------------------------------------------------------------------------------
