---------------------------------------------------------------------------------------------------------
Problem              inst_100_50_100_50_75_25_45_01_12.cmpl
Nr. of variables     1000000
Nr. of constraints   35050
Objective name       cost
Solver name          GLPK
Display variables    nonzero variables (all)
Display constraints  nonzero constraints (all)
---------------------------------------------------------------------------------------------------------

Objective status     integer feasible (non-optimal)
Objective value      53366 (min!)

Variables 
Name                 Type            Activity         Lower bound         Upper bound            Marginal
---------------------------------------------------------------------------------------------------------
y[1,69,71,1]            I                   1                   0                   1                   -
y[1,71,37,2]            I                   1                   0                   1                   -
y[2,22,20,1]            I                   1                   0                   1                   -
y[2,27,22,1]            I                   1                   0                   1                   -
y[2,29,27,1]            I                   1                   0                   1                   -
y[2,53,29,2]            I                   1                   0                   1                   -
y[2,54,53,1]            I                   1                   0                   1                   -
y[3,63,65,1]            I                   1                   0                   1                   -
y[3,65,66,1]            I                   1                   0                   1                   -
y[3,66,13,2]            I                   1                   0                   1                   -
y[4,82,85,1]            I                   1                   0                   1                   -
y[4,85,48,2]            I                   1                   0                   1                   -
y[5,55,56,1]            I                   1                   0                   1                   -
y[5,56,55,1]            I                   1                   0                   1                   -
y[5,66,52,2]            I                   1                   0                   1                   -
y[5,68,66,1]            I                   1                   0                   1                   -
y[5,79,68,1]            I                   1                   0                   1                   -
y[6,92,78,1]            I                   1                   0                   1                   -
y[7,5,4,1]              I                   1                   0                   1                   -
y[7,22,5,2]             I                   1                   0                   1                   -
y[7,23,22,1]            I                   1                   0                   1                   -
y[7,93,23,2]            I                   1                   0                   1                   -
y[7,94,93,1]            I                   1                   0                   1                   -
y[8,96,90,1]            I                   1                   0                   1                   -
y[8,98,96,1]            I                   1                   0                   1                   -
y[9,32,26,1]            I                   1                   0                   1                   -
y[9,33,32,1]            I                   1                   0                   1                   -
y[9,35,33,1]            I                   1                   0                   1                   -
y[9,47,35,2]            I                   1                   0                   1                   -
y[9,50,47,1]            I                   1                   0                   1                   -
y[9,53,50,1]            I                   1                   0                   1                   -
y[10,87,89,1]           I                   1                   0                   1                   -
y[11,26,34,1]           I                   1                   0                   1                   -
y[11,34,58,2]           I                   1                   0                   1                   -
y[11,58,59,1]           I                   1                   0                   1                   -
y[11,59,60,1]           I                   1                   0                   1                   -
y[12,69,59,2]           I                   1                   0                   1                   -
y[12,72,69,1]           I                   1                   0                   1                   -
y[12,73,72,1]           I                   1                   0                   1                   -
y[13,96,88,1]           I                   1                   0                   1                   -
y[14,21,19,1]           I                   1                   0                   1                   -
y[14,25,21,1]           I                   1                   0                   1                   -
y[14,26,25,1]           I                   1                   0                   1                   -
y[15,62,64,1]           I                   1                   0                   1                   -
y[15,64,78,1]           I                   1                   0                   1                   -
y[15,78,79,1]           I                   1                   0                   1                   -
y[16,44,43,1]           I                   1                   0                   1                   -
y[16,47,44,1]           I                   1                   0                   1                   -
y[16,48,47,1]           I                   1                   0                   1                   -
y[16,85,48,2]           I                   1                   0                   1                   -
y[16,86,85,1]           I                   1                   0                   1                   -
y[16,87,86,1]           I                   1                   0                   1                   -
y[16,88,87,1]           I                   1                   0                   1                   -
y[16,90,88,1]           I                   1                   0                   1                   -
y[16,91,90,1]           I                   1                   0                   1                   -
y[16,92,91,1]           I                   1                   0                   1                   -
y[17,5,4,1]             I                   1                   0                   1                   -
y[17,48,5,2]            I                   1                   0                   1                   -
y[17,49,48,1]           I                   1                   0                   1                   -
y[17,97,49,2]           I                   1                   0                   1                   -
y[18,55,60,1]           I                   1                   0                   1                   -
y[19,12,10,1]           I                   1                   0                   1                   -
y[19,13,12,1]           I                   1                   0                   1                   -
y[19,15,13,1]           I                   1                   0                   1                   -
y[19,83,15,2]           I                   1                   0                   1                   -
y[19,87,83,1]           I                   1                   0                   1                   -
y[20,27,24,2]           I                   1                   0                   1                   -
y[20,46,27,2]           I                   1                   0                   1                   -
y[20,51,46,1]           I                   1                   0                   1                   -
y[20,55,51,1]           I                   1                   0                   1                   -
y[20,56,55,1]           I                   1                   0                   1                   -
y[20,57,56,1]           I                   1                   0                   1                   -
y[20,58,57,1]           I                   1                   0                   1                   -
y[21,1,36,2]            I                   1                   0                   1                   -
y[21,36,37,1]           I                   1                   0                   1                   -
y[21,37,53,2]           I                   1                   0                   1                   -
y[21,53,54,1]           I                   1                   0                   1                   -
y[22,40,54,2]           I                   1                   0                   1                   -
y[22,54,60,1]           I                   1                   0                   1                   -
y[23,6,5,1]             I                   1                   0                   1                   -
y[23,16,6,2]            I                   1                   0                   1                   -
y[23,24,16,1]           I                   1                   0                   1                   -
y[23,25,24,1]           I                   1                   0                   1                   -
y[24,46,64,2]           I                   1                   0                   1                   -
y[24,64,65,1]           I                   1                   0                   1                   -
y[25,12,13,1]           I                   1                   0                   1                   -
y[25,13,16,1]           I                   1                   0                   1                   -
y[26,8,10,1]            I                   1                   0                   1                   -
y[26,10,31,2]           I                   1                   0                   1                   -
y[26,31,34,1]           I                   1                   0                   1                   -
y[26,34,36,1]           I                   1                   0                   1                   -
y[26,36,38,1]           I                   1                   0                   1                   -
y[27,76,70,1]           I                   1                   0                   1                   -
y[27,77,76,1]           I                   1                   0                   1                   -
y[27,85,77,1]           I                   1                   0                   1                   -
y[28,6,4,1]             I                   1                   0                   1                   -
y[28,7,6,1]             I                   1                   0                   1                   -
y[29,61,62,1]           I                   1                   0                   1                   -
y[29,62,63,1]           I                   1                   0                   1                   -
y[29,63,65,1]           I                   1                   0                   1                   -
y[29,65,80,2]           I                   1                   0                   1                   -
y[29,80,81,1]           I                   1                   0                   1                   -
y[30,71,72,1]           I                   1                   0                   1                   -
y[31,43,38,1]           I                   1                   0                   1                   -
y[31,76,43,2]           I                   1                   0                   1                   -
y[31,77,76,1]           I                   1                   0                   1                   -
y[31,93,77,2]           I                   1                   0                   1                   -
y[32,57,58,1]           I                   1                   0                   1                   -
y[32,58,60,1]           I                   1                   0                   1                   -
y[32,60,88,2]           I                   1                   0                   1                   -
y[32,88,90,1]           I                   1                   0                   1                   -
y[32,90,91,1]           I                   1                   0                   1                   -
y[33,22,48,2]           I                   1                   0                   1                   -
y[33,24,22,1]           I                   1                   0                   1                   -
y[33,25,24,1]           I                   1                   0                   1                   -
y[33,48,49,1]           I                   1                   0                   1                   -
y[33,49,51,1]           I                   1                   0                   1                   -
y[34,42,39,1]           I                   1                   0                   1                   -
y[34,54,42,2]           I                   1                   0                   1                   -
y[34,55,54,1]           I                   1                   0                   1                   -
y[34,56,55,1]           I                   1                   0                   1                   -
y[34,77,78,1]           I                   1                   0                   1                   -
y[34,78,77,1]           I                   1                   0                   1                   -
y[34,79,56,2]           I                   1                   0                   1                   -
y[34,81,79,1]           I                   1                   0                   1                   -
y[34,89,81,1]           I                   1                   0                   1                   -
y[34,90,89,1]           I                   1                   0                   1                   -
y[34,93,90,1]           I                   1                   0                   1                   -
y[34,95,93,1]           I                   1                   0                   1                   -
y[35,3,2,1]             I                   1                   0                   1                   -
y[35,37,38,1]           I                   1                   0                   1                   -
y[35,38,40,1]           I                   1                   0                   1                   -
y[35,40,3,2]            I                   1                   0                   1                   -
y[36,3,13,1]            I                   1                   0                   1                   -
y[37,59,81,2]           I                   1                   0                   1                   -
y[37,61,59,1]           I                   1                   0                   1                   -
y[37,62,61,1]           I                   1                   0                   1                   -
y[37,81,82,1]           I                   1                   0                   1                   -
y[37,82,83,1]           I                   1                   0                   1                   -
y[38,5,6,1]             I                   1                   0                   1                   -
y[38,6,8,1]             I                   1                   0                   1                   -
y[38,8,9,1]             I                   1                   0                   1                   -
y[38,9,68,2]            I                   1                   0                   1                   -
y[39,30,31,1]           I                   1                   0                   1                   -
y[39,31,37,2]           I                   1                   0                   1                   -
y[39,37,42,1]           I                   1                   0                   1                   -
y[39,42,97,2]           I                   1                   0                   1                   -
y[39,97,98,1]           I                   1                   0                   1                   -
y[40,96,97,1]           I                   1                   0                   1                   -
y[40,97,29,2]           I                   1                   0                   1                   -
y[41,68,66,1]           I                   1                   0                   1                   -
y[41,69,68,1]           I                   1                   0                   1                   -
y[41,71,72,1]           I                   1                   0                   1                   -
y[41,72,69,1]           I                   1                   0                   1                   -
y[41,92,71,2]           I                   1                   0                   1                   -
y[41,93,92,1]           I                   1                   0                   1                   -
y[41,95,93,1]           I                   1                   0                   1                   -
y[42,37,42,1]           I                   1                   0                   1                   -
y[42,42,45,1]           I                   1                   0                   1                   -
y[42,45,47,1]           I                   1                   0                   1                   -
y[42,47,51,1]           I                   1                   0                   1                   -
y[43,21,22,1]           I                   1                   0                   1                   -
y[43,22,48,2]           I                   1                   0                   1                   -
y[43,48,49,1]           I                   1                   0                   1                   -
y[44,5,7,1]             I                   1                   0                   1                   -
y[44,7,11,1]            I                   1                   0                   1                   -
y[45,11,12,1]           I                   1                   0                   1                   -
y[45,12,13,1]           I                   1                   0                   1                   -
y[45,13,28,2]           I                   1                   0                   1                   -
y[45,28,30,1]           I                   1                   0                   1                   -
y[45,30,38,1]           I                   1                   0                   1                   -
y[45,38,67,2]           I                   1                   0                   1                   -
y[46,84,83,1]           I                   1                   0                   1                   -
y[46,85,84,1]           I                   1                   0                   1                   -
y[47,89,86,1]           I                   1                   0                   1                   -
y[47,90,89,1]           I                   1                   0                   1                   -
y[47,93,90,1]           I                   1                   0                   1                   -
y[47,94,93,1]           I                   1                   0                   1                   -
y[47,95,94,1]           I                   1                   0                   1                   -
y[47,97,95,1]           I                   1                   0                   1                   -
y[48,64,62,1]           I                   1                   0                   1                   -
y[48,78,64,2]           I                   1                   0                   1                   -
y[48,79,78,1]           I                   1                   0                   1                   -
y[48,94,79,2]           I                   1                   0                   1                   -
y[49,78,42,2]           I                   1                   0                   1                   -
y[49,84,78,1]           I                   1                   0                   1                   -
y[49,87,84,1]           I                   1                   0                   1                   -
y[49,88,87,1]           I                   1                   0                   1                   -
y[50,50,49,1]           I                   1                   0                   1                   -
---------------------------------------------------------------------------------------------------------

Constraints 
Name                 Type            Activity         Lower bound         Upper bound            Marginal
---------------------------------------------------------------------------------------------------------
bilancio[1,21]          E                  -1                  -1                  -1                   -
bilancio[2,35]          E                   1                   1                   1                   -
bilancio[3,36]          E                  -1                  -1                  -1                   -
bilancio[4,7]           E                   1                   1                   1                   -
bilancio[4,17]          E                   1                   1                   1                   -
bilancio[4,28]          E                   1                   1                   1                   -
bilancio[5,23]          E                   1                   1                   1                   -
bilancio[5,38]          E                  -1                  -1                  -1                   -
bilancio[5,44]          E                  -1                  -1                  -1                   -
bilancio[7,28]          E                  -1                  -1                  -1                   -
bilancio[8,26]          E                  -1                  -1                  -1                   -
bilancio[10,19]         E                   1                   1                   1                   -
bilancio[11,44]         E                   1                   1                   1                   -
bilancio[11,45]         E                  -1                  -1                  -1                   -
bilancio[12,25]         E                  -1                  -1                  -1                   -
bilancio[13,3]          E                   1                   1                   1                   -
bilancio[13,36]         E                   1                   1                   1                   -
bilancio[16,25]         E                   1                   1                   1                   -
bilancio[19,14]         E                   1                   1                   1                   -
bilancio[20,2]          E                   1                   1                   1                   -
bilancio[21,43]         E                  -1                  -1                  -1                   -
bilancio[24,20]         E                   1                   1                   1                   -
bilancio[25,23]         E                  -1                  -1                  -1                   -
bilancio[25,33]         E                  -1                  -1                  -1                   -
bilancio[26,9]          E                   1                   1                   1                   -
bilancio[26,11]         E                  -1                  -1                  -1                   -
bilancio[26,14]         E                  -1                  -1                  -1                   -
bilancio[29,40]         E                   1                   1                   1                   -
bilancio[30,39]         E                  -1                  -1                  -1                   -
bilancio[37,1]          E                   1                   1                   1                   -
bilancio[37,35]         E                  -1                  -1                  -1                   -
bilancio[37,42]         E                  -1                  -1                  -1                   -
bilancio[38,26]         E                   1                   1                   1                   -
bilancio[38,31]         E                   1                   1                   1                   -
bilancio[39,34]         E                   1                   1                   1                   -
bilancio[40,22]         E                  -1                  -1                  -1                   -
bilancio[42,49]         E                   1                   1                   1                   -
bilancio[43,16]         E                   1                   1                   1                   -
bilancio[46,24]         E                  -1                  -1                  -1                   -
bilancio[48,4]          E                   1                   1                   1                   -
bilancio[49,43]         E                   1                   1                   1                   -
bilancio[49,50]         E                   1                   1                   1                   -
bilancio[50,50]         E                  -1                  -1                  -1                   -
bilancio[51,33]         E                   1                   1                   1                   -
bilancio[51,42]         E                   1                   1                   1                   -
bilancio[52,5]          E                   1                   1                   1                   -
bilancio[53,9]          E                  -1                  -1                  -1                   -
bilancio[54,2]          E                  -1                  -1                  -1                   -
bilancio[54,21]         E                   1                   1                   1                   -
bilancio[55,18]         E                  -1                  -1                  -1                   -
bilancio[57,32]         E                  -1                  -1                  -1                   -
bilancio[58,20]         E                  -1                  -1                  -1                   -
bilancio[59,12]         E                   1                   1                   1                   -
bilancio[60,11]         E                   1                   1                   1                   -
bilancio[60,18]         E                   1                   1                   1                   -
bilancio[60,22]         E                   1                   1                   1                   -
bilancio[61,29]         E                  -1                  -1                  -1                   -
bilancio[62,15]         E                  -1                  -1                  -1                   -
bilancio[62,37]         E                  -1                  -1                  -1                   -
bilancio[62,48]         E                   1                   1                   1                   -
bilancio[63,3]          E                  -1                  -1                  -1                   -
bilancio[65,24]         E                   1                   1                   1                   -
bilancio[66,41]         E                   1                   1                   1                   -
bilancio[67,45]         E                   1                   1                   1                   -
bilancio[68,38]         E                   1                   1                   1                   -
bilancio[69,1]          E                  -1                  -1                  -1                   -
bilancio[70,27]         E                   1                   1                   1                   -
bilancio[71,30]         E                  -1                  -1                  -1                   -
bilancio[72,30]         E                   1                   1                   1                   -
bilancio[73,12]         E                  -1                  -1                  -1                   -
bilancio[78,6]          E                   1                   1                   1                   -
bilancio[79,5]          E                  -1                  -1                  -1                   -
bilancio[79,15]         E                   1                   1                   1                   -
bilancio[81,29]         E                   1                   1                   1                   -
bilancio[82,4]          E                  -1                  -1                  -1                   -
bilancio[83,37]         E                   1                   1                   1                   -
bilancio[83,46]         E                   1                   1                   1                   -
bilancio[85,27]         E                  -1                  -1                  -1                   -
bilancio[85,46]         E                  -1                  -1                  -1                   -
bilancio[86,47]         E                   1                   1                   1                   -
bilancio[87,10]         E                  -1                  -1                  -1                   -
bilancio[87,19]         E                  -1                  -1                  -1                   -
bilancio[88,13]         E                   1                   1                   1                   -
bilancio[88,49]         E                  -1                  -1                  -1                   -
bilancio[89,10]         E                   1                   1                   1                   -
bilancio[90,8]          E                   1                   1                   1                   -
bilancio[91,32]         E                   1                   1                   1                   -
bilancio[92,6]          E                  -1                  -1                  -1                   -
bilancio[92,16]         E                  -1                  -1                  -1                   -
bilancio[93,31]         E                  -1                  -1                  -1                   -
bilancio[94,7]          E                  -1                  -1                  -1                   -
bilancio[94,48]         E                  -1                  -1                  -1                   -
bilancio[95,34]         E                  -1                  -1                  -1                   -
bilancio[95,41]         E                  -1                  -1                  -1                   -
bilancio[96,13]         E                  -1                  -1                  -1                   -
bilancio[96,40]         E                  -1                  -1                  -1                   -
bilancio[97,17]         E                  -1                  -1                  -1                   -
bilancio[97,47]         E                  -1                  -1                  -1                   -
bilancio[98,8]          E                  -1                  -1                  -1                   -
bilancio[98,39]         E                   1                   1                   1                   -
capacity[1,36,2]        L                  88           -Infinity                 106                   -
capacity[3,2,1]         L                  82           -Infinity                 217                   -
capacity[3,13,1]        L                  53           -Infinity                 199                   -
capacity[5,4,1]         L                 123           -Infinity                 191                   -
capacity[5,6,1]         L                  97           -Infinity                 199                   -
capacity[5,7,1]         L                  85           -Infinity                 103                   -
capacity[6,4,1]         L                  91           -Infinity                 253                   -
capacity[6,5,1]         L                  99           -Infinity                 265                   -
capacity[6,8,1]         L                  97           -Infinity                 289                   -
capacity[7,6,1]         L                  91           -Infinity                 219                   -
capacity[7,11,1]        L                  85           -Infinity                 135                   -
capacity[8,9,1]         L                  97           -Infinity                 158                   -
capacity[8,10,1]        L                  77           -Infinity                 119                   -
capacity[9,68,2]        L                  97           -Infinity                 112                   -
capacity[10,31,2]       L                  77           -Infinity                 134                   -
capacity[11,12,1]       L                  62           -Infinity                 213                   -
capacity[12,10,1]       L                  87           -Infinity                 275                   -
capacity[12,13,1]       L                 116           -Infinity                 269                   -
capacity[13,12,1]       L                  87           -Infinity                 184                   -
capacity[13,16,1]       L                  54           -Infinity                 196                   -
capacity[13,28,2]       L                  62           -Infinity                 126                   -
capacity[15,13,1]       L                  87           -Infinity                 118                   -
capacity[16,6,2]        L                  99           -Infinity                 139                   -
capacity[21,19,1]       L                  80           -Infinity                 177                   -
capacity[21,22,1]       L                  50           -Infinity                 121                   -
capacity[22,5,2]        L                  65           -Infinity                 109                   -
capacity[22,20,1]       L                  70           -Infinity                 204                   -
capacity[22,48,2]       L                 127           -Infinity                 135                   -
capacity[23,22,1]       L                  65           -Infinity                 298                   -
capacity[24,16,1]       L                  99           -Infinity                 287                   -
capacity[24,22,1]       L                  77           -Infinity                 104                   -
capacity[25,21,1]       L                  80           -Infinity                 232                   -
capacity[25,24,1]       L                 176           -Infinity                 222                   -
capacity[26,25,1]       L                  80           -Infinity                 121                   -
capacity[26,34,1]       L                  64           -Infinity                 291                   -
capacity[27,22,1]       L                  70           -Infinity                 181                   -
capacity[27,24,2]       L                  73           -Infinity                 113                   -
capacity[28,30,1]       L                  62           -Infinity                 134                   -
capacity[29,27,1]       L                  70           -Infinity                 277                   -
capacity[30,31,1]       L                  97           -Infinity                 210                   -
capacity[30,38,1]       L                  62           -Infinity                 278                   -
capacity[31,34,1]       L                  77           -Infinity                 158                   -
capacity[31,37,2]       L                  97           -Infinity                 119                   -
capacity[32,26,1]       L                  63           -Infinity                 157                   -
capacity[33,32,1]       L                  63           -Infinity                 120                   -
capacity[34,36,1]       L                  77           -Infinity                 132                   -
capacity[34,58,2]       L                  64           -Infinity                 143                   -
capacity[35,33,1]       L                  63           -Infinity                 178                   -
capacity[36,37,1]       L                  88           -Infinity                 279                   -
capacity[36,38,1]       L                  77           -Infinity                 297                   -
capacity[37,38,1]       L                  82           -Infinity                 238                   -
capacity[37,42,1]       L                 182           -Infinity                 183                   -
capacity[37,53,2]       L                  88           -Infinity                 105                   -
capacity[38,40,1]       L                  82           -Infinity                 219                   -
capacity[38,67,2]       L                  62           -Infinity                 110                   -
capacity[40,3,2]        L                  82           -Infinity                 105                   -
capacity[40,54,2]       L                  93           -Infinity                 136                   -
capacity[42,39,1]       L                  76           -Infinity                 117                   -
capacity[42,45,1]       L                  85           -Infinity                 237                   -
capacity[42,97,2]       L                  97           -Infinity                 150                   -
capacity[43,38,1]       L                  57           -Infinity                 111                   -
capacity[44,43,1]       L                  70           -Infinity                 108                   -
capacity[45,47,1]       L                  85           -Infinity                 171                   -
capacity[46,27,2]       L                  73           -Infinity                 119                   -
capacity[46,64,2]       L                  89           -Infinity                 140                   -
capacity[47,35,2]       L                  63           -Infinity                 112                   -
capacity[47,44,1]       L                  70           -Infinity                 156                   -
capacity[47,51,1]       L                  85           -Infinity                 148                   -
capacity[48,5,2]        L                  58           -Infinity                 109                   -
capacity[48,47,1]       L                  70           -Infinity                 290                   -
capacity[48,49,1]       L                 127           -Infinity                 214                   -
capacity[49,48,1]       L                  58           -Infinity                 257                   -
capacity[49,51,1]       L                  77           -Infinity                 130                   -
capacity[50,47,1]       L                  63           -Infinity                 292                   -
capacity[50,49,1]       L                  78           -Infinity                 244                   -
capacity[51,46,1]       L                  73           -Infinity                 263                   -
capacity[53,29,2]       L                  70           -Infinity                 103                   -
capacity[53,50,1]       L                  63           -Infinity                 193                   -
capacity[53,54,1]       L                  88           -Infinity                 210                   -
capacity[54,42,2]       L                  76           -Infinity                 107                   -
capacity[54,53,1]       L                  70           -Infinity                 250                   -
capacity[54,60,1]       L                  93           -Infinity                 290                   -
capacity[55,51,1]       L                  73           -Infinity                 273                   -
capacity[55,54,1]       L                  76           -Infinity                 242                   -
capacity[55,56,1]       L                  62           -Infinity                 129                   -
capacity[55,60,1]       L                  98           -Infinity                 104                   -
capacity[56,55,1]       L                 211           -Infinity                 287                   -
capacity[57,56,1]       L                  73           -Infinity                 266                   -
capacity[57,58,1]       L                  96           -Infinity                 196                   -
capacity[58,57,1]       L                  73           -Infinity                 179                   -
capacity[58,59,1]       L                  64           -Infinity                 165                   -
capacity[58,60,1]       L                  96           -Infinity                 137                   -
capacity[59,60,1]       L                  64           -Infinity                 106                   -
capacity[59,81,2]       L                  79           -Infinity                 101                   -
capacity[60,88,2]       L                  96           -Infinity                 116                   -
capacity[61,59,1]       L                  79           -Infinity                 165                   -
capacity[61,62,1]       L                  84           -Infinity                 137                   -
capacity[62,61,1]       L                  79           -Infinity                 172                   -
capacity[62,63,1]       L                  84           -Infinity                 107                   -
capacity[62,64,1]       L                  61           -Infinity                 144                   -
capacity[63,65,1]       L                 151           -Infinity                 257                   -
capacity[64,62,1]       L                  95           -Infinity                 121                   -
capacity[64,65,1]       L                  89           -Infinity                 187                   -
capacity[64,78,1]       L                  61           -Infinity                 225                   -
capacity[65,66,1]       L                  67           -Infinity                 260                   -
capacity[65,80,2]       L                  84           -Infinity                 122                   -
capacity[66,13,2]       L                  67           -Infinity                 121                   -
capacity[66,52,2]       L                  62           -Infinity                 149                   -
capacity[68,66,1]       L                 133           -Infinity                 272                   -
capacity[69,59,2]       L                  85           -Infinity                 114                   -
capacity[69,68,1]       L                  71           -Infinity                 195                   -
capacity[69,71,1]       L                  53           -Infinity                 249                   -
capacity[71,37,2]       L                  53           -Infinity                 132                   -
capacity[71,72,1]       L                 135           -Infinity                 146                   -
capacity[72,69,1]       L                 156           -Infinity                 292                   -
capacity[73,72,1]       L                  85           -Infinity                 226                   -
capacity[76,43,2]       L                  57           -Infinity                 119                   -
capacity[76,70,1]       L                 100           -Infinity                 224                   -
capacity[77,76,1]       L                 157           -Infinity                 236                   -
capacity[77,78,1]       L                  76           -Infinity                 135                   -
capacity[78,42,2]       L                  61           -Infinity                 126                   -
capacity[78,64,2]       L                  95           -Infinity                 108                   -
capacity[78,77,1]       L                  76           -Infinity                 216                   -
capacity[78,79,1]       L                  61           -Infinity                 256                   -
capacity[79,56,2]       L                  76           -Infinity                 103                   -
capacity[79,68,1]       L                  62           -Infinity                 286                   -
capacity[79,78,1]       L                  95           -Infinity                 134                   -
capacity[80,81,1]       L                  84           -Infinity                 116                   -
capacity[81,79,1]       L                  76           -Infinity                 279                   -
capacity[81,82,1]       L                  79           -Infinity                 261                   -
capacity[82,83,1]       L                  79           -Infinity                 154                   -
capacity[82,85,1]       L                  50           -Infinity                 280                   -
capacity[83,15,2]       L                  87           -Infinity                 150                   -
capacity[84,78,1]       L                  61           -Infinity                 129                   -
capacity[84,83,1]       L                  78           -Infinity                 158                   -
capacity[85,48,2]       L                 120           -Infinity                 137                   -
capacity[85,77,1]       L                 100           -Infinity                 213                   -
capacity[85,84,1]       L                  78           -Infinity                 290                   -
capacity[86,85,1]       L                  70           -Infinity                 186                   -
capacity[87,83,1]       L                  87           -Infinity                 103                   -
capacity[87,84,1]       L                  61           -Infinity                 230                   -
capacity[87,86,1]       L                  70           -Infinity                 206                   -
capacity[87,89,1]       L                  50           -Infinity                 130                   -
capacity[88,87,1]       L                 131           -Infinity                 198                   -
capacity[88,90,1]       L                  96           -Infinity                 250                   -
capacity[89,81,1]       L                  76           -Infinity                 105                   -
capacity[89,86,1]       L                  94           -Infinity                 300                   -
capacity[90,88,1]       L                  70           -Infinity                 143                   -
capacity[90,89,1]       L                 170           -Infinity                 174                   -
capacity[90,91,1]       L                  96           -Infinity                 255                   -
capacity[91,90,1]       L                  70           -Infinity                 218                   -
capacity[92,71,2]       L                  71           -Infinity                 108                   -
capacity[92,78,1]       L                  93           -Infinity                 250                   -
capacity[92,91,1]       L                  70           -Infinity                 144                   -
capacity[93,23,2]       L                  65           -Infinity                 127                   -
capacity[93,77,2]       L                  57           -Infinity                 103                   -
capacity[93,90,1]       L                 170           -Infinity                 253                   -
capacity[93,92,1]       L                  71           -Infinity                 242                   -
capacity[94,79,2]       L                  95           -Infinity                 112                   -
capacity[94,93,1]       L                 159           -Infinity                 240                   -
capacity[95,93,1]       L                 147           -Infinity                 286                   -
capacity[95,94,1]       L                  94           -Infinity                 154                   -
capacity[96,88,1]       L                  71           -Infinity                 254                   -
capacity[96,90,1]       L                  78           -Infinity                 202                   -
capacity[96,97,1]       L                  67           -Infinity                 282                   -
capacity[97,29,2]       L                  67           -Infinity                 128                   -
capacity[97,49,2]       L                  58           -Infinity                 137                   -
capacity[97,95,1]       L                  94           -Infinity                 208                   -
capacity[97,98,1]       L                  97           -Infinity                 288                   -
capacity[98,96,1]       L                  78           -Infinity                 233                   -
lunghezza[1]            L                   2           -Infinity                  12                   -
lunghezza[2]            L                   5           -Infinity                  12                   -
lunghezza[3]            L                   3           -Infinity                  12                   -
lunghezza[4]            L                   2           -Infinity                  12                   -
lunghezza[5]            L                   5           -Infinity                  12                   -
lunghezza[6]            L                   1           -Infinity                  12                   -
lunghezza[7]            L                   5           -Infinity                  12                   -
lunghezza[8]            L                   2           -Infinity                  12                   -
lunghezza[9]            L                   6           -Infinity                  12                   -
lunghezza[10]           L                   1           -Infinity                  12                   -
lunghezza[11]           L                   4           -Infinity                  12                   -
lunghezza[12]           L                   3           -Infinity                  12                   -
lunghezza[13]           L                   1           -Infinity                  12                   -
lunghezza[14]           L                   3           -Infinity                  12                   -
lunghezza[15]           L                   3           -Infinity                  12                   -
lunghezza[16]           L                  10           -Infinity                  12                   -
lunghezza[17]           L                   4           -Infinity                  12                   -
lunghezza[18]           L                   1           -Infinity                  12                   -
lunghezza[19]           L                   5           -Infinity                  12                   -
lunghezza[20]           L                   7           -Infinity                  12                   -
lunghezza[21]           L                   4           -Infinity                  12                   -
lunghezza[22]           L                   2           -Infinity                  12                   -
lunghezza[23]           L                   4           -Infinity                  12                   -
lunghezza[24]           L                   2           -Infinity                  12                   -
lunghezza[25]           L                   2           -Infinity                  12                   -
lunghezza[26]           L                   5           -Infinity                  12                   -
lunghezza[27]           L                   3           -Infinity                  12                   -
lunghezza[28]           L                   2           -Infinity                  12                   -
lunghezza[29]           L                   5           -Infinity                  12                   -
lunghezza[30]           L                   1           -Infinity                  12                   -
lunghezza[31]           L                   4           -Infinity                  12                   -
lunghezza[32]           L                   5           -Infinity                  12                   -
lunghezza[33]           L                   5           -Infinity                  12                   -
lunghezza[34]           L                  12           -Infinity                  12                   -
lunghezza[35]           L                   4           -Infinity                  12                   -
lunghezza[36]           L                   1           -Infinity                  12                   -
lunghezza[37]           L                   5           -Infinity                  12                   -
lunghezza[38]           L                   4           -Infinity                  12                   -
lunghezza[39]           L                   5           -Infinity                  12                   -
lunghezza[40]           L                   2           -Infinity                  12                   -
lunghezza[41]           L                   7           -Infinity                  12                   -
lunghezza[42]           L                   4           -Infinity                  12                   -
lunghezza[43]           L                   3           -Infinity                  12                   -
lunghezza[44]           L                   2           -Infinity                  12                   -
lunghezza[45]           L                   6           -Infinity                  12                   -
lunghezza[46]           L                   2           -Infinity                  12                   -
lunghezza[47]           L                   6           -Infinity                  12                   -
lunghezza[48]           L                   4           -Infinity                  12                   -
lunghezza[49]           L                   4           -Infinity                  12                   -
lunghezza[50]           L                   1           -Infinity                  12                   -
unico[1,69,1]           L                   1           -Infinity                   1                   -
unico[1,71,2]           L                   1           -Infinity                   1                   -
unico[2,22,1]           L                   1           -Infinity                   1                   -
unico[2,27,1]           L                   1           -Infinity                   1                   -
unico[2,29,1]           L                   1           -Infinity                   1                   -
unico[2,53,2]           L                   1           -Infinity                   1                   -
unico[2,54,1]           L                   1           -Infinity                   1                   -
unico[3,63,1]           L                   1           -Infinity                   1                   -
unico[3,65,1]           L                   1           -Infinity                   1                   -
unico[3,66,2]           L                   1           -Infinity                   1                   -
unico[4,82,1]           L                   1           -Infinity                   1                   -
unico[4,85,2]           L                   1           -Infinity                   1                   -
unico[5,55,1]           L                   1           -Infinity                   1                   -
unico[5,56,1]           L                   1           -Infinity                   1                   -
unico[5,66,2]           L                   1           -Infinity                   1                   -
unico[5,68,1]           L                   1           -Infinity                   1                   -
unico[5,79,1]           L                   1           -Infinity                   1                   -
unico[6,92,1]           L                   1           -Infinity                   1                   -
unico[7,5,1]            L                   1           -Infinity                   1                   -
unico[7,22,2]           L                   1           -Infinity                   1                   -
unico[7,23,1]           L                   1           -Infinity                   1                   -
unico[7,93,2]           L                   1           -Infinity                   1                   -
unico[7,94,1]           L                   1           -Infinity                   1                   -
unico[8,96,1]           L                   1           -Infinity                   1                   -
unico[8,98,1]           L                   1           -Infinity                   1                   -
unico[9,32,1]           L                   1           -Infinity                   1                   -
unico[9,33,1]           L                   1           -Infinity                   1                   -
unico[9,35,1]           L                   1           -Infinity                   1                   -
unico[9,47,2]           L                   1           -Infinity                   1                   -
unico[9,50,1]           L                   1           -Infinity                   1                   -
unico[9,53,1]           L                   1           -Infinity                   1                   -
unico[10,87,1]          L                   1           -Infinity                   1                   -
unico[11,26,1]          L                   1           -Infinity                   1                   -
unico[11,34,2]          L                   1           -Infinity                   1                   -
unico[11,58,1]          L                   1           -Infinity                   1                   -
unico[11,59,1]          L                   1           -Infinity                   1                   -
unico[12,69,2]          L                   1           -Infinity                   1                   -
unico[12,72,1]          L                   1           -Infinity                   1                   -
unico[12,73,1]          L                   1           -Infinity                   1                   -
unico[13,96,1]          L                   1           -Infinity                   1                   -
unico[14,21,1]          L                   1           -Infinity                   1                   -
unico[14,25,1]          L                   1           -Infinity                   1                   -
unico[14,26,1]          L                   1           -Infinity                   1                   -
unico[15,62,1]          L                   1           -Infinity                   1                   -
unico[15,64,1]          L                   1           -Infinity                   1                   -
unico[15,78,1]          L                   1           -Infinity                   1                   -
unico[16,44,1]          L                   1           -Infinity                   1                   -
unico[16,47,1]          L                   1           -Infinity                   1                   -
unico[16,48,1]          L                   1           -Infinity                   1                   -
unico[16,85,2]          L                   1           -Infinity                   1                   -
unico[16,86,1]          L                   1           -Infinity                   1                   -
unico[16,87,1]          L                   1           -Infinity                   1                   -
unico[16,88,1]          L                   1           -Infinity                   1                   -
unico[16,90,1]          L                   1           -Infinity                   1                   -
unico[16,91,1]          L                   1           -Infinity                   1                   -
unico[16,92,1]          L                   1           -Infinity                   1                   -
unico[17,5,1]           L                   1           -Infinity                   1                   -
unico[17,48,2]          L                   1           -Infinity                   1                   -
unico[17,49,1]          L                   1           -Infinity                   1                   -
unico[17,97,2]          L                   1           -Infinity                   1                   -
unico[18,55,1]          L                   1           -Infinity                   1                   -
unico[19,12,1]          L                   1           -Infinity                   1                   -
unico[19,13,1]          L                   1           -Infinity                   1                   -
unico[19,15,1]          L                   1           -Infinity                   1                   -
unico[19,83,2]          L                   1           -Infinity                   1                   -
unico[19,87,1]          L                   1           -Infinity                   1                   -
unico[20,27,2]          L                   1           -Infinity                   1                   -
unico[20,46,2]          L                   1           -Infinity                   1                   -
unico[20,51,1]          L                   1           -Infinity                   1                   -
unico[20,55,1]          L                   1           -Infinity                   1                   -
unico[20,56,1]          L                   1           -Infinity                   1                   -
unico[20,57,1]          L                   1           -Infinity                   1                   -
unico[20,58,1]          L                   1           -Infinity                   1                   -
unico[21,1,2]           L                   1           -Infinity                   1                   -
unico[21,36,1]          L                   1           -Infinity                   1                   -
unico[21,37,2]          L                   1           -Infinity                   1                   -
unico[21,53,1]          L                   1           -Infinity                   1                   -
unico[22,40,2]          L                   1           -Infinity                   1                   -
unico[22,54,1]          L                   1           -Infinity                   1                   -
unico[23,6,1]           L                   1           -Infinity                   1                   -
unico[23,16,2]          L                   1           -Infinity                   1                   -
unico[23,24,1]          L                   1           -Infinity                   1                   -
unico[23,25,1]          L                   1           -Infinity                   1                   -
unico[24,46,2]          L                   1           -Infinity                   1                   -
unico[24,64,1]          L                   1           -Infinity                   1                   -
unico[25,12,1]          L                   1           -Infinity                   1                   -
unico[25,13,1]          L                   1           -Infinity                   1                   -
unico[26,8,1]           L                   1           -Infinity                   1                   -
unico[26,10,2]          L                   1           -Infinity                   1                   -
unico[26,31,1]          L                   1           -Infinity                   1                   -
unico[26,34,1]          L                   1           -Infinity                   1                   -
unico[26,36,1]          L                   1           -Infinity                   1                   -
unico[27,76,1]          L                   1           -Infinity                   1                   -
unico[27,77,1]          L                   1           -Infinity                   1                   -
unico[27,85,1]          L                   1           -Infinity                   1                   -
unico[28,6,1]           L                   1           -Infinity                   1                   -
unico[28,7,1]           L                   1           -Infinity                   1                   -
unico[29,61,1]          L                   1           -Infinity                   1                   -
unico[29,62,1]          L                   1           -Infinity                   1                   -
unico[29,63,1]          L                   1           -Infinity                   1                   -
unico[29,65,2]          L                   1           -Infinity                   1                   -
unico[29,80,1]          L                   1           -Infinity                   1                   -
unico[30,71,1]          L                   1           -Infinity                   1                   -
unico[31,43,1]          L                   1           -Infinity                   1                   -
unico[31,76,2]          L                   1           -Infinity                   1                   -
unico[31,77,1]          L                   1           -Infinity                   1                   -
unico[31,93,2]          L                   1           -Infinity                   1                   -
unico[32,57,1]          L                   1           -Infinity                   1                   -
unico[32,58,1]          L                   1           -Infinity                   1                   -
unico[32,60,2]          L                   1           -Infinity                   1                   -
unico[32,88,1]          L                   1           -Infinity                   1                   -
unico[32,90,1]          L                   1           -Infinity                   1                   -
unico[33,22,2]          L                   1           -Infinity                   1                   -
unico[33,24,1]          L                   1           -Infinity                   1                   -
unico[33,25,1]          L                   1           -Infinity                   1                   -
unico[33,48,1]          L                   1           -Infinity                   1                   -
unico[33,49,1]          L                   1           -Infinity                   1                   -
unico[34,42,1]          L                   1           -Infinity                   1                   -
unico[34,54,2]          L                   1           -Infinity                   1                   -
unico[34,55,1]          L                   1           -Infinity                   1                   -
unico[34,56,1]          L                   1           -Infinity                   1                   -
unico[34,77,1]          L                   1           -Infinity                   1                   -
unico[34,78,1]          L                   1           -Infinity                   1                   -
unico[34,79,2]          L                   1           -Infinity                   1                   -
unico[34,81,1]          L                   1           -Infinity                   1                   -
unico[34,89,1]          L                   1           -Infinity                   1                   -
unico[34,90,1]          L                   1           -Infinity                   1                   -
unico[34,93,1]          L                   1           -Infinity                   1                   -
unico[34,95,1]          L                   1           -Infinity                   1                   -
unico[35,3,1]           L                   1           -Infinity                   1                   -
unico[35,37,1]          L                   1           -Infinity                   1                   -
unico[35,38,1]          L                   1           -Infinity                   1                   -
unico[35,40,2]          L                   1           -Infinity                   1                   -
unico[36,3,1]           L                   1           -Infinity                   1                   -
unico[37,59,2]          L                   1           -Infinity                   1                   -
unico[37,61,1]          L                   1           -Infinity                   1                   -
unico[37,62,1]          L                   1           -Infinity                   1                   -
unico[37,81,1]          L                   1           -Infinity                   1                   -
unico[37,82,1]          L                   1           -Infinity                   1                   -
unico[38,5,1]           L                   1           -Infinity                   1                   -
unico[38,6,1]           L                   1           -Infinity                   1                   -
unico[38,8,1]           L                   1           -Infinity                   1                   -
unico[38,9,2]           L                   1           -Infinity                   1                   -
unico[39,30,1]          L                   1           -Infinity                   1                   -
unico[39,31,2]          L                   1           -Infinity                   1                   -
unico[39,37,1]          L                   1           -Infinity                   1                   -
unico[39,42,2]          L                   1           -Infinity                   1                   -
unico[39,97,1]          L                   1           -Infinity                   1                   -
unico[40,96,1]          L                   1           -Infinity                   1                   -
unico[40,97,2]          L                   1           -Infinity                   1                   -
unico[41,68,1]          L                   1           -Infinity                   1                   -
unico[41,69,1]          L                   1           -Infinity                   1                   -
unico[41,71,1]          L                   1           -Infinity                   1                   -
unico[41,72,1]          L                   1           -Infinity                   1                   -
unico[41,92,2]          L                   1           -Infinity                   1                   -
unico[41,93,1]          L                   1           -Infinity                   1                   -
unico[41,95,1]          L                   1           -Infinity                   1                   -
unico[42,37,1]          L                   1           -Infinity                   1                   -
unico[42,42,1]          L                   1           -Infinity                   1                   -
unico[42,45,1]          L                   1           -Infinity                   1                   -
unico[42,47,1]          L                   1           -Infinity                   1                   -
unico[43,21,1]          L                   1           -Infinity                   1                   -
unico[43,22,2]          L                   1           -Infinity                   1                   -
unico[43,48,1]          L                   1           -Infinity                   1                   -
unico[44,5,1]           L                   1           -Infinity                   1                   -
unico[44,7,1]           L                   1           -Infinity                   1                   -
unico[45,11,1]          L                   1           -Infinity                   1                   -
unico[45,12,1]          L                   1           -Infinity                   1                   -
unico[45,13,2]          L                   1           -Infinity                   1                   -
unico[45,28,1]          L                   1           -Infinity                   1                   -
unico[45,30,1]          L                   1           -Infinity                   1                   -
unico[45,38,2]          L                   1           -Infinity                   1                   -
unico[46,84,1]          L                   1           -Infinity                   1                   -
unico[46,85,1]          L                   1           -Infinity                   1                   -
unico[47,89,1]          L                   1           -Infinity                   1                   -
unico[47,90,1]          L                   1           -Infinity                   1                   -
unico[47,93,1]          L                   1           -Infinity                   1                   -
unico[47,94,1]          L                   1           -Infinity                   1                   -
unico[47,95,1]          L                   1           -Infinity                   1                   -
unico[47,97,1]          L                   1           -Infinity                   1                   -
unico[48,64,1]          L                   1           -Infinity                   1                   -
unico[48,78,2]          L                   1           -Infinity                   1                   -
unico[48,79,1]          L                   1           -Infinity                   1                   -
unico[48,94,2]          L                   1           -Infinity                   1                   -
unico[49,78,2]          L                   1           -Infinity                   1                   -
unico[49,84,1]          L                   1           -Infinity                   1                   -
unico[49,87,1]          L                   1           -Infinity                   1                   -
unico[49,88,1]          L                   1           -Infinity                   1                   -
unico[50,50,1]          L                   1           -Infinity                   1                   -
---------------------------------------------------------------------------------------------------------
