---------------------------------------------------------------------------------------------------------
Problem              inst_50_50_100_50_75_25_45$_01_13.cmpl
Nr. of variables     125000
Nr. of constraints   8800
Objective name       cost
Solver name          GLPK
Display variables    nonzero variables (all)
Display constraints  nonzero constraints (all)
---------------------------------------------------------------------------------------------------------

Objective status     optimal
Objective value      3898 (min!)

Variables 
Name                 Type            Activity         Lower bound         Upper bound            Marginal
---------------------------------------------------------------------------------------------------------
y[1,40,44,2]            I                   1                   0                   1                   -
y[1,41,40,1]            I                   1                   0                   1                   -
y[1,44,4,2]             I                   1                   0                   1                   -
y[2,15,17,1]            I                   1                   0                   1                   -
y[2,17,21,2]            I                   1                   0                   1                   -
y[2,21,20,1]            I                   1                   0                   1                   -
y[2,37,42,2]            I                   1                   0                   1                   -
y[2,42,15,2]            I                   1                   0                   1                   -
y[3,20,18,1]            I                   1                   0                   1                   -
y[3,25,20,2]            I                   1                   0                   1                   -
y[3,45,25,2]            I                   1                   0                   1                   -
y[4,1,20,2]             I                   1                   0                   1                   -
y[4,11,38,2]            I                   1                   0                   1                   -
y[4,19,41,2]            I                   1                   0                   1                   -
y[4,20,19,1]            I                   1                   0                   1                   -
y[4,38,37,1]            I                   1                   0                   1                   -
y[4,41,11,2]            I                   1                   0                   1                   -
y[5,1,3,1]              I                   1                   0                   1                   -
y[5,3,22,2]             I                   1                   0                   1                   -
y[5,22,34,2]            I                   1                   0                   1                   -
y[6,6,8,1]              I                   1                   0                   1                   -
y[6,8,35,2]             I                   1                   0                   1                   -
y[6,35,36,1]            I                   1                   0                   1                   -
y[7,26,27,1]            I                   1                   0                   1                   -
y[7,44,26,2]            I                   1                   0                   1                   -
y[8,9,23,2]             I                   1                   0                   1                   -
y[9,7,42,2]             I                   1                   0                   1                   -
y[9,42,2,2]             I                   1                   0                   1                   -
y[9,50,7,2]             I                   1                   0                   1                   -
y[10,21,20,1]           I                   1                   0                   1                   -
y[11,7,8,1]             I                   1                   0                   1                   -
y[11,8,9,1]             I                   1                   0                   1                   -
y[12,2,3,1]             I                   1                   0                   1                   -
y[12,50,2,2]            I                   1                   0                   1                   -
y[13,8,7,1]             I                   1                   0                   1                   -
y[13,21,45,2]           I                   1                   0                   1                   -
y[13,25,8,2]            I                   1                   0                   1                   -
y[13,45,25,2]           I                   1                   0                   1                   -
y[14,22,40,2]           I                   1                   0                   1                   -
y[15,12,45,2]           I                   1                   0                   1                   -
y[15,36,37,1]           I                   1                   0                   1                   -
y[15,37,12,2]           I                   1                   0                   1                   -
y[15,45,44,1]           I                   1                   0                   1                   -
y[16,9,8,1]             I                   1                   0                   1                   -
y[16,22,23,1]           I                   1                   0                   1                   -
y[16,23,9,2]            I                   1                   0                   1                   -
y[17,4,29,2]            I                   1                   0                   1                   -
y[17,34,4,2]            I                   1                   0                   1                   -
y[17,35,34,1]           I                   1                   0                   1                   -
y[18,14,49,2]           I                   1                   0                   1                   -
y[18,17,14,1]           I                   1                   0                   1                   -
y[18,49,50,1]           I                   1                   0                   1                   -
y[19,31,32,1]           I                   1                   0                   1                   -
y[19,32,50,2]           I                   1                   0                   1                   -
y[19,50,2,2]            I                   1                   0                   1                   -
y[20,25,26,1]           I                   1                   0                   1                   -
y[20,26,27,1]           I                   1                   0                   1                   -
y[20,40,41,1]           I                   1                   0                   1                   -
y[20,41,25,2]           I                   1                   0                   1                   -
y[21,12,13,1]           I                   1                   0                   1                   -
y[21,28,29,1]           I                   1                   0                   1                   -
y[21,29,30,1]           I                   1                   0                   1                   -
y[21,30,12,2]           I                   1                   0                   1                   -
y[22,33,7,2]            I                   1                   0                   1                   -
y[22,35,33,1]           I                   1                   0                   1                   -
y[22,36,35,1]           I                   1                   0                   1                   -
y[23,9,7,1]             I                   1                   0                   1                   -
y[23,20,21,1]           I                   1                   0                   1                   -
y[23,21,9,2]            I                   1                   0                   1                   -
y[24,29,28,1]           I                   1                   0                   1                   -
y[24,30,29,1]           I                   1                   0                   1                   -
y[24,31,30,1]           I                   1                   0                   1                   -
y[25,22,21,1]           I                   1                   0                   1                   -
---------------------------------------------------------------------------------------------------------

Constraints 
Name                 Type            Activity         Lower bound         Upper bound            Marginal
---------------------------------------------------------------------------------------------------------
bilancio[1,4]           E                  -1                  -1                  -1                   -
bilancio[1,5]           E                  -1                  -1                  -1                   -
bilancio[2,9]           E                   1                   1                   1                   -
bilancio[2,19]          E                   1                   1                   1                   -
bilancio[3,12]          E                   1                   1                   1                   -
bilancio[4,1]           E                   1                   1                   1                   -
bilancio[6,6]           E                  -1                  -1                  -1                   -
bilancio[7,11]          E                  -1                  -1                  -1                   -
bilancio[7,13]          E                   1                   1                   1                   -
bilancio[7,22]          E                   1                   1                   1                   -
bilancio[7,23]          E                   1                   1                   1                   -
bilancio[8,16]          E                   1                   1                   1                   -
bilancio[9,8]           E                  -1                  -1                  -1                   -
bilancio[9,11]          E                   1                   1                   1                   -
bilancio[13,21]         E                   1                   1                   1                   -
bilancio[17,18]         E                  -1                  -1                  -1                   -
bilancio[18,3]          E                   1                   1                   1                   -
bilancio[20,2]          E                   1                   1                   1                   -
bilancio[20,10]         E                   1                   1                   1                   -
bilancio[20,23]         E                  -1                  -1                  -1                   -
bilancio[21,10]         E                  -1                  -1                  -1                   -
bilancio[21,13]         E                  -1                  -1                  -1                   -
bilancio[21,25]         E                   1                   1                   1                   -
bilancio[22,14]         E                  -1                  -1                  -1                   -
bilancio[22,16]         E                  -1                  -1                  -1                   -
bilancio[22,25]         E                  -1                  -1                  -1                   -
bilancio[23,8]          E                   1                   1                   1                   -
bilancio[27,7]          E                   1                   1                   1                   -
bilancio[27,20]         E                   1                   1                   1                   -
bilancio[28,21]         E                  -1                  -1                  -1                   -
bilancio[28,24]         E                   1                   1                   1                   -
bilancio[29,17]         E                   1                   1                   1                   -
bilancio[31,19]         E                  -1                  -1                  -1                   -
bilancio[31,24]         E                  -1                  -1                  -1                   -
bilancio[34,5]          E                   1                   1                   1                   -
bilancio[35,17]         E                  -1                  -1                  -1                   -
bilancio[36,6]          E                   1                   1                   1                   -
bilancio[36,15]         E                  -1                  -1                  -1                   -
bilancio[36,22]         E                  -1                  -1                  -1                   -
bilancio[37,2]          E                  -1                  -1                  -1                   -
bilancio[37,4]          E                   1                   1                   1                   -
bilancio[40,14]         E                   1                   1                   1                   -
bilancio[40,20]         E                  -1                  -1                  -1                   -
bilancio[41,1]          E                  -1                  -1                  -1                   -
bilancio[44,7]          E                  -1                  -1                  -1                   -
bilancio[44,15]         E                   1                   1                   1                   -
bilancio[45,3]          E                  -1                  -1                  -1                   -
bilancio[50,9]          E                  -1                  -1                  -1                   -
bilancio[50,12]         E                  -1                  -1                  -1                   -
bilancio[50,18]         E                   1                   1                   1                   -
capacity[1,3,1]         L                  52           -Infinity                 213                   -
capacity[1,20,2]        L                  53           -Infinity                 115                   -
capacity[2,3,1]         L                  51           -Infinity                 177                   -
capacity[3,22,2]        L                  52           -Infinity                 132                   -
capacity[4,29,2]        L                  53           -Infinity                 113                   -
capacity[6,8,1]         L                  53           -Infinity                 266                   -
capacity[7,8,1]         L                  65           -Infinity                 227                   -
capacity[7,42,2]        L                  83           -Infinity                 115                   -
capacity[8,7,1]         L                  64           -Infinity                 214                   -
capacity[8,9,1]         L                  65           -Infinity                 254                   -
capacity[8,35,2]        L                  53           -Infinity                 117                   -
capacity[9,7,1]         L                  92           -Infinity                 109                   -
capacity[9,8,1]         L                  62           -Infinity                 116                   -
capacity[9,23,2]        L                  87           -Infinity                 107                   -
capacity[11,38,2]       L                  53           -Infinity                 113                   -
capacity[12,13,1]       L                  88           -Infinity                 253                   -
capacity[12,45,2]       L                  64           -Infinity                 141                   -
capacity[14,49,2]       L                  76           -Infinity                 133                   -
capacity[15,17,1]       L                  86           -Infinity                 229                   -
capacity[17,14,1]       L                  76           -Infinity                 119                   -
capacity[17,21,2]       L                  86           -Infinity                 109                   -
capacity[19,41,2]       L                  53           -Infinity                 107                   -
capacity[20,18,1]       L                  54           -Infinity                 193                   -
capacity[20,19,1]       L                  53           -Infinity                 220                   -
capacity[20,21,1]       L                  92           -Infinity                 147                   -
capacity[21,9,2]        L                  92           -Infinity                 116                   -
capacity[21,20,1]       L                 185           -Infinity                 195                   -
capacity[21,45,2]       L                  64           -Infinity                 103                   -
capacity[22,21,1]       L                  52           -Infinity                 298                   -
capacity[22,23,1]       L                  62           -Infinity                 284                   -
capacity[22,34,2]       L                  52           -Infinity                 114                   -
capacity[22,40,2]       L                  50           -Infinity                 100                   -
capacity[23,9,2]        L                  62           -Infinity                 134                   -
capacity[25,8,2]        L                  64           -Infinity                 101                   -
capacity[25,20,2]       L                  54           -Infinity                 135                   -
capacity[25,26,1]       L                  83           -Infinity                 142                   -
capacity[26,27,1]       L                 145           -Infinity                 168                   -
capacity[28,29,1]       L                  88           -Infinity                 128                   -
capacity[29,28,1]       L                  77           -Infinity                 244                   -
capacity[29,30,1]       L                  88           -Infinity                 113                   -
capacity[30,12,2]       L                  88           -Infinity                 105                   -
capacity[30,29,1]       L                  77           -Infinity                 134                   -
capacity[31,30,1]       L                  77           -Infinity                 295                   -
capacity[31,32,1]       L                  53           -Infinity                 104                   -
capacity[32,50,2]       L                  53           -Infinity                 142                   -
capacity[33,7,2]        L                  93           -Infinity                 103                   -
capacity[34,4,2]        L                  53           -Infinity                 118                   -
capacity[35,33,1]       L                  93           -Infinity                 127                   -
capacity[35,34,1]       L                  53           -Infinity                 230                   -
capacity[35,36,1]       L                  53           -Infinity                 271                   -
capacity[36,35,1]       L                  93           -Infinity                 144                   -
capacity[36,37,1]       L                  64           -Infinity                 113                   -
capacity[37,12,2]       L                  64           -Infinity                 147                   -
capacity[37,42,2]       L                  86           -Infinity                 124                   -
capacity[38,37,1]       L                  53           -Infinity                 293                   -
capacity[40,41,1]       L                  83           -Infinity                 153                   -
capacity[40,44,2]       L                  58           -Infinity                 113                   -
capacity[41,11,2]       L                  53           -Infinity                 128                   -
capacity[41,25,2]       L                  83           -Infinity                 127                   -
capacity[41,40,1]       L                  58           -Infinity                 133                   -
capacity[42,2,2]        L                  83           -Infinity                 131                   -
capacity[42,15,2]       L                  86           -Infinity                 140                   -
capacity[44,4,2]        L                  58           -Infinity                 109                   -
capacity[44,26,2]       L                  62           -Infinity                 104                   -
capacity[45,25,2]       L                 118           -Infinity                 150                   -
capacity[45,44,1]       L                  64           -Infinity                 224                   -
capacity[49,50,1]       L                  76           -Infinity                 252                   -
capacity[50,2,2]        L                 104           -Infinity                 126                   -
capacity[50,7,2]        L                  83           -Infinity                 147                   -
lunghezza[1,1]          L                   1           -Infinity                  13                   -
lunghezza[1,2]          L                   2           -Infinity                  13                   -
lunghezza[2,1]          L                   2           -Infinity                  13                   -
lunghezza[2,2]          L                   3           -Infinity                  13                   -
lunghezza[3,1]          L                   1           -Infinity                  13                   -
lunghezza[3,2]          L                   2           -Infinity                  13                   -
lunghezza[4,1]          L                   2           -Infinity                  13                   -
lunghezza[4,2]          L                   4           -Infinity                  13                   -
lunghezza[5,1]          L                   1           -Infinity                  13                   -
lunghezza[5,2]          L                   2           -Infinity                  13                   -
lunghezza[6,1]          L                   2           -Infinity                  13                   -
lunghezza[6,2]          L                   1           -Infinity                  13                   -
lunghezza[7,1]          L                   1           -Infinity                  13                   -
lunghezza[7,2]          L                   1           -Infinity                  13                   -
lunghezza[8,2]          L                   1           -Infinity                  13                   -
lunghezza[9,2]          L                   3           -Infinity                  13                   -
lunghezza[10,1]         L                   1           -Infinity                  13                   -
lunghezza[11,1]         L                   2           -Infinity                  13                   -
lunghezza[12,1]         L                   1           -Infinity                  13                   -
lunghezza[12,2]         L                   1           -Infinity                  13                   -
lunghezza[13,1]         L                   1           -Infinity                  13                   -
lunghezza[13,2]         L                   3           -Infinity                  13                   -
lunghezza[14,2]         L                   1           -Infinity                  13                   -
lunghezza[15,1]         L                   2           -Infinity                  13                   -
lunghezza[15,2]         L                   2           -Infinity                  13                   -
lunghezza[16,1]         L                   2           -Infinity                  13                   -
lunghezza[16,2]         L                   1           -Infinity                  13                   -
lunghezza[17,1]         L                   1           -Infinity                  13                   -
lunghezza[17,2]         L                   2           -Infinity                  13                   -
lunghezza[18,1]         L                   2           -Infinity                  13                   -
lunghezza[18,2]         L                   1           -Infinity                  13                   -
lunghezza[19,1]         L                   1           -Infinity                  13                   -
lunghezza[19,2]         L                   2           -Infinity                  13                   -
lunghezza[20,1]         L                   3           -Infinity                  13                   -
lunghezza[20,2]         L                   1           -Infinity                  13                   -
lunghezza[21,1]         L                   3           -Infinity                  13                   -
lunghezza[21,2]         L                   1           -Infinity                  13                   -
lunghezza[22,1]         L                   2           -Infinity                  13                   -
lunghezza[22,2]         L                   1           -Infinity                  13                   -
lunghezza[23,1]         L                   2           -Infinity                  13                   -
lunghezza[23,2]         L                   1           -Infinity                  13                   -
lunghezza[24,1]         L                   3           -Infinity                  13                   -
lunghezza[25,1]         L                   1           -Infinity                  13                   -
unico[1,40,2]           L                   1           -Infinity                   1                   -
unico[1,41,1]           L                   1           -Infinity                   1                   -
unico[1,44,2]           L                   1           -Infinity                   1                   -
unico[2,15,1]           L                   1           -Infinity                   1                   -
unico[2,17,2]           L                   1           -Infinity                   1                   -
unico[2,21,1]           L                   1           -Infinity                   1                   -
unico[2,37,2]           L                   1           -Infinity                   1                   -
unico[2,42,2]           L                   1           -Infinity                   1                   -
unico[3,20,1]           L                   1           -Infinity                   1                   -
unico[3,25,2]           L                   1           -Infinity                   1                   -
unico[3,45,2]           L                   1           -Infinity                   1                   -
unico[4,1,2]            L                   1           -Infinity                   1                   -
unico[4,11,2]           L                   1           -Infinity                   1                   -
unico[4,19,2]           L                   1           -Infinity                   1                   -
unico[4,20,1]           L                   1           -Infinity                   1                   -
unico[4,38,1]           L                   1           -Infinity                   1                   -
unico[4,41,2]           L                   1           -Infinity                   1                   -
unico[5,1,1]            L                   1           -Infinity                   1                   -
unico[5,3,2]            L                   1           -Infinity                   1                   -
unico[5,22,2]           L                   1           -Infinity                   1                   -
unico[6,6,1]            L                   1           -Infinity                   1                   -
unico[6,8,2]            L                   1           -Infinity                   1                   -
unico[6,35,1]           L                   1           -Infinity                   1                   -
unico[7,26,1]           L                   1           -Infinity                   1                   -
unico[7,44,2]           L                   1           -Infinity                   1                   -
unico[8,9,2]            L                   1           -Infinity                   1                   -
unico[9,7,2]            L                   1           -Infinity                   1                   -
unico[9,42,2]           L                   1           -Infinity                   1                   -
unico[9,50,2]           L                   1           -Infinity                   1                   -
unico[10,21,1]          L                   1           -Infinity                   1                   -
unico[11,7,1]           L                   1           -Infinity                   1                   -
unico[11,8,1]           L                   1           -Infinity                   1                   -
unico[12,2,1]           L                   1           -Infinity                   1                   -
unico[12,50,2]          L                   1           -Infinity                   1                   -
unico[13,8,1]           L                   1           -Infinity                   1                   -
unico[13,21,2]          L                   1           -Infinity                   1                   -
unico[13,25,2]          L                   1           -Infinity                   1                   -
unico[13,45,2]          L                   1           -Infinity                   1                   -
unico[14,22,2]          L                   1           -Infinity                   1                   -
unico[15,12,2]          L                   1           -Infinity                   1                   -
unico[15,36,1]          L                   1           -Infinity                   1                   -
unico[15,37,2]          L                   1           -Infinity                   1                   -
unico[15,45,1]          L                   1           -Infinity                   1                   -
unico[16,9,1]           L                   1           -Infinity                   1                   -
unico[16,22,1]          L                   1           -Infinity                   1                   -
unico[16,23,2]          L                   1           -Infinity                   1                   -
unico[17,4,2]           L                   1           -Infinity                   1                   -
unico[17,34,2]          L                   1           -Infinity                   1                   -
unico[17,35,1]          L                   1           -Infinity                   1                   -
unico[18,14,2]          L                   1           -Infinity                   1                   -
unico[18,17,1]          L                   1           -Infinity                   1                   -
unico[18,49,1]          L                   1           -Infinity                   1                   -
unico[19,31,1]          L                   1           -Infinity                   1                   -
unico[19,32,2]          L                   1           -Infinity                   1                   -
unico[19,50,2]          L                   1           -Infinity                   1                   -
unico[20,25,1]          L                   1           -Infinity                   1                   -
unico[20,26,1]          L                   1           -Infinity                   1                   -
unico[20,40,1]          L                   1           -Infinity                   1                   -
unico[20,41,2]          L                   1           -Infinity                   1                   -
unico[21,12,1]          L                   1           -Infinity                   1                   -
unico[21,28,1]          L                   1           -Infinity                   1                   -
unico[21,29,1]          L                   1           -Infinity                   1                   -
unico[21,30,2]          L                   1           -Infinity                   1                   -
unico[22,33,2]          L                   1           -Infinity                   1                   -
unico[22,35,1]          L                   1           -Infinity                   1                   -
unico[22,36,1]          L                   1           -Infinity                   1                   -
unico[23,9,1]           L                   1           -Infinity                   1                   -
unico[23,20,1]          L                   1           -Infinity                   1                   -
unico[23,21,2]          L                   1           -Infinity                   1                   -
unico[24,29,1]          L                   1           -Infinity                   1                   -
unico[24,30,1]          L                   1           -Infinity                   1                   -
unico[24,31,1]          L                   1           -Infinity                   1                   -
unico[25,22,1]          L                   1           -Infinity                   1                   -
---------------------------------------------------------------------------------------------------------
